# Generated by Django 5.1.6 on 2025-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_category_name_category_category_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
