# Generated by Django 5.1.6 on 2025-03-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_db",
            new_name="parent_category",
        ),
    ]
