# Generated by Django 5.1.6 on 2025-03-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_product_category_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="no_photo.jpg", upload_to="products_photo/"
            ),
        ),
    ]
