# Generated by Django 5.1.6 on 2025-03-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.product",
            ),
        ),
    ]
