# Generated by Django 5.1.6 on 2025-03-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_product_category_category_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
        ),
    ]
