# Generated by Django 5.1.6 on 2025-03-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="products", to="store.category"),
        ),
    ]
