# Generated by Django 5.1.6 on 2025-03-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parent",
            new_name="parent_category",
        ),
    ]
